{% set name = "rpm-tools" %}
{% set version = "4.17.1" %}
{% set major_minor = ".".join(version.split(".")[:-1]) %}

package:
  name: {{ name|lower }}
  version: {{ version }}


source:
  url: http://ftp.rpm.org/releases/rpm-{{ major_minor }}.x/rpm-{{ version }}.tar.bz2
  sha256: 0c11b793466e7258851ff82bd65c8ffd8c2dbbc70acc869a5d34150549926e5d

build:
  number: 3
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - make
    - cmake
    - pkg-config
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
  host:
    - python       # [linux]
    - pip          # [linux]
    - elfutils     # [linux]
    - libarchive
    - libcap       # [linux]
    - libgcrypt
    - lmdb
    - lua
    - nss
    - popt
    - libdb
    - zstd
    - xz
    - bzip2
    - libiconv
    - file
    - zlib
  run:
    - python                            # [linux]
    - {{ pin_compatible('elfutils') }}  # [linux]
    - {{ pin_compatible('nss') }}
    - {{ pin_compatible('file') }}

test:
  imports:   # [linux]
    - rpm    # [linux]
  commands:
    - rpm --help

about:
  home: https://rpm.org/index.html
  license: GPL-2.0-or-later OR LGPL-2.0-or-later
  license_file: COPYING
  summary: The RPM Package Manager
  description: |
    The RPM Package Manager (RPM) is a powerful package management system capable of:

    * building computer software from source into easily distributable packages
    * installing, updating and uninstalling packaged software
    * querying detailed information about the packaged software, whether installed or not
    * verifying integrity of packaged software and resulting software installation

  doc_url: https://rpm.org/documentation.html
  dev_url: https://github.com/rpm-software-management/rpm/

extra:
  recipe-maintainers:
    - chrisburr
