schema_version: 1

context:
  name: rpm-tools
  version: 4.20.1
  major_minor: "\"\".\".join(version | split(\".\")[:-1])\""

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: http://ftp.rpm.org/releases/rpm-${{ major_minor }}.x/rpm-${{ version }}.tar.bz2
  sha256: 52647e12638364533ab671cbc8e485c96f9f08889d93fe0ed104a6632661124f

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - make
    - cmake
    - pkg-config
    - if: osx
      then: llvm-openmp
    - if: linux
      then: libgomp
  host:
    - if: linux
      then: python
    - if: linux
      then: pip
    - if: linux
      then: elfutils
    - libarchive
    - if: linux
      then: libcap
    - libgcrypt
    - lmdb
    - lua
    - nss
    - popt
    - libdb
    - zstd
    - liblzma-devel
    - bzip2
    - libiconv
    - file
    - zlib
  run:
    - if: linux
      then: python
    - if: linux
      then: ${{ pin_compatible('elfutils') }}
    - ${{ pin_compatible('nss') }}
    - ${{ pin_compatible('file') }}

tests:
  - python:
      imports:
        - rpm
  - script:
      - rpm --help

about:
  license: GPL-2.0-or-later OR LGPL-2.0-or-later
  license_file: COPYING
  summary: The RPM Package Manager
  description: |
    The RPM Package Manager (RPM) is a powerful package management system capable of:

    * building computer software from source into easily distributable packages
    * installing, updating and uninstalling packaged software
    * querying detailed information about the packaged software, whether installed or not
    * verifying integrity of packaged software and resulting software installation

  homepage: https://rpm.org/index.html
  repository: https://github.com/rpm-software-management/rpm/
  documentation: https://rpm.org/documentation.html

extra:
  recipe-maintainers:
    - chrisburr
